export const products = [
  // 💎 DIAMOND COLLECTION
  {
    id: "d1",
    name: "Black Carbon Diamond",
    price: 1600,
    image: "/products/diamond-9.jpg",
    category: "Unisex",
  },
  {
    id: "d2",
    name: "White Regent Diamond",
    price: 1600,
    image: "/products/diamond-10.jpg",
    category: "Unisex",
  },
  {
    id: "d3",
    name: "Sapphire Leather",
    price: 1600,
    image: "/products/tobacco-1.jpg",
    category: "Men",
  },
  {
    id: "d4",
    name: "Emerald Soul Diamond",
    price: 1600,
    image: "/products/tobacco-2.jpg",
    category: "Unisex",
  },
  {
    id: "d5",
    name: "Purple Heart Diamond",
    price: 1600,
    image: "/products/tobacco-3.jpg",
    category: "Women",
  },
  {
    id: "d6",
    name: "Grey Pearl Diamond",
    price: 1600,
    image: "/products/tobacco-4.jpg",
    category: "Unisex",
  },
  {
    id: "d7",
    name: "Black Diamond Incense",
    price: 1600,
    image: "/products/tobacco-5.jpg",
    category: "Men",
  },
  {
    id: "d8",
    name: "Pink Diamond Sakura",
    price: 1600,
    image: "/products/tobacco-6.jpg",
    category: "Women",
  },
  {
    id: "d9",
    name: "Blue Diamond Aqua",
    price: 1600,
    image: "/products/tobacco-7.jpg",
    category: "Unisex",
  },
  {
    id: "d10",
    name: "Nude Coral Diamond",
    price: 1600,
    image: "/products/دايموند.jpg",
    category: "Unisex",
  },

  // 🚬 TOBACCO COLLECTION
  {
    id: "t1",
    name: "Greek Tobacco",
    price: 1600,
    image: "/products/diamond-1.jpg",
    category: "Unisex",
  },
  {
    id: "t2",
    name: "Jamaican Tobacco",
    price: 1600,
    image: "/products/diamond-2.jpg",
    category: "Men",
  },
  {
    id: "t3",
    name: "Mexican Tobacco",
    price: 1600,
    image: "/products/diamond-3.jpg",
    category: "Men",
  },
  {
    id: "t4",
    name: "Brazilian Tobacco",
    price: 1600,
    image: "/products/diamond-4.jpg",
    category: "Men",
  },
  {
    id: "t5",
    name: "Dominican Tobacco",
    price: 1600,
    image: "/products/diamond-5.jpg",
    category: "Men",
  },
  {
    id: "t6",
    name: "Spanish Tobacco",
    price: 1600,
    image: "/products/diamond-6.jpg",
    category: "Men",
  },
  {
    id: "t7",
    name: "French Tobacco",
    price: 1600,
    image: "/products/diamond-8.jpg",
    category: "Unisex",
  },
  {
    id: "t8",
    name: "Cuban Tobacco",
    price: 1600,
    image: "/products/diamond-7.jpg",
    category: "Men",
  },
];