export const products = [
  // 💎 DIAMOND COLLECTION
  {
    id: "d1",
    name: "Black Carbon Diamond",
    price: 1600,
    image: "/products/diamond-9.jpg",
    category: "Unisex",
  },
  {
    id: "d2",
    name: "White Regent Diamond",
    price: 1600,
    image: "/products/diamond-10.jpg",
    category: "Unisex",
  },
  {
    id: "d3",
    name: "Sapphire Leather",
    price: 1600,
    image: "/products/tobacco-1.jpg",
    category: "Men",
  },
  {
    id: "d4",
    name: "Emerald Soul Diamond",
    price: 1600,
    image: "/products/tobacco-2.jpg",
    category: "Unisex",
  },
  {
    id: "d5",
    name: "Purple Heart Diamond",
    price: 1600,
    image: "/products/tobacco-3.jpg",
    category: "Women",
  },
  {
    id: "d6",
    name: "Grey Pearl Diamond",
    price: 1600,
    image: "/products/tobacco-4.jpg",
    category: "Unisex",
  },
  {
    id: "d7",
    name: "Black Diamond Incense",
    price: 1600,
    image: "/products/tobacco-5.jpg",
    category: "Men",
  },
  {
    id: "d8",
    name: "Pink Diamond Sakura",
    price: 1600,
    image: "/products/tobacco-6.jpg",
    category: "Women",
  },
  {
    id: "d9",
    name: "Blue Diamond Aqua",
    price: 1600,
    image: "/products/tobacco-7.jpg",
    category: "Unisex",
  },
  {
    id: "d10",
    name: "Nude Coral Diamond",
    price: 1600,
    image: "/products/دايموند.jpg",
    category: "Unisex",
  },

  // 🚬 TOBACCO COLLECTION
  {
    id: "t1",
    name: "Greek Tobacco",
    price: 1600,
    image: "/products/diamond-1.jpg",
    category: "Unisex",
  },
  {
    id: "t2",
    name: "Jamaican Tobacco",
    price: 1600,
    image: "/products/diamond-2.jpg",
    category: "Men",
  },
  {
    id: "t3",
    name: "Mexican Tobacco",
    price: 1600,
    image: "/products/diamond-3.jpg",
    category: "Men",
  },
  {
    id: "t4",
    name: "Brazilian Tobacco",
    price: 1600,
    image: "/products/diamond-4.jpg",
    category: "Men",
  },
  {
    id: "t5",
    name: "Dominican Tobacco",
    price: 1600,
    image: "/products/diamond-5.jpg",
    category: "Men",
  },
  {
    id: "t6",
    name: "Spanish Tobacco",
    price: 1600,
    image: "/products/diamond-6.jpg",
    category: "Men",
  },
  {
    id: "t7",
    name: "French Tobacco",
    price: 1600,
    image: "/products/diamond-8.jpg",
    category: "Unisex",
  },
  {
    id: "t8",
    name: "Cuban Tobacco",
    price: 1600,
    image: "/products/diamond-7.jpg",
    category: "Men",
  },
   // Assaf Main Collection

  {
    id: 1,
    name: "Afternoon",
    brand: "Assaf",
    collection: "Assaf Main Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/afternoon.jpeg",
  },

  {
    id: 2,
    name: "Black Elixir",
    brand: "Assaf",
    collection: "Assaf Main Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/Frankel_Black_Elixir.jpeg",
  },

  {
    id: 3,
    name: "Challenge",
    brand: "Assaf",
    collection: "Assaf Main Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/Challenge.jpeg",
  },

  {
    id: 4,
    name: "Elysium",
    brand: "Assaf",
    collection: "Assaf Main Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/elysium.jpeg",
  },

  {
    id: 5,
    name: "Frankel Silver Elixir",
    brand: "Assaf",
    collection: "Assaf Main Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/frankel-silver-elixir.jpeg",
  },

  {
    id: 6,
    name: "Green Irish",
    brand: "Assaf",
    collection: "Assaf Main Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/green-irish.jpeg",
  },

  {
    id: 7,
    name: "Gris Erik",
    brand: "Assaf",
    collection: "Assaf Main Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/Gris_Erik_Luxury.jpeg",
  },

  {
    id: 8,
    name: "I Am Here",
    brand: "Assaf",
    collection: "Assaf Main Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/i-am-here.jpeg",
  },

  {
    id: 9,
    name: "Miss Gris Intense",
    brand: "Assaf",
    collection: "Assaf Main Collection",
    gender: "Women",
    price: 1000,
    image: "/products/assaf/miss-gris-intense.jpeg",
  },

  {
    id: 10,
    name: "Miss Gris Dance",
    brand: "Assaf",
    collection: "Assaf Main Collection",
    gender: "Women",
    price: 1000,
    image: "/products/assaf/Miss_Gris_Dance.jpeg",
  },

  {
    id: 11,
    name: "Miss Sakura",
    brand: "Assaf",
    collection: "Assaf Main Collection",
    gender: "Women",
    price: 1000,
    image: "/products/assaf/miss-sakura.jpeg",
  },

  {
    id: 12,
    name: "No Comment",
    brand: "Assaf",
    collection: "Assaf Main Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/no-comment.jpeg",
  },

  {
    id: 13,
    name: "Risk Comete",
    brand: "Assaf",
    collection: "Assaf Main Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/risk-comete.jpeg",
  },

  {
    id: 14,
    name: "Storm",
    brand: "Assaf",
    collection: "Assaf Main Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/Frankel_Storm.jpeg",
  },

  {
    id: 15,
    name: "Wild Colt",
    brand: "Assaf",
    collection: "Assaf Main Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/wild-colt.jpeg",
  },

  {
    id: 16,
    name: "Reflection",
    brand: "Assaf",
    collection: "Assaf Main Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/reflection.jpeg",
  },

  {
    id: 17,
    name: "Tobacco Black 40",
    brand: "Assaf",
    collection: "Tobacco Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/tobacco-black-40.jpeg",
  },

  {
    id: 18,
    name: "Tobacco Jam",
    brand: "Assaf",
    collection: "Tobacco Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/tobacco-jam.jpeg",
  },

  {
    id: 19,
    name: "Tobacco Jam 50",
    brand: "Assaf",
    collection: "Tobacco Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/tobacco-jam-50.jpeg",
  },

  {
    id: 20,
    name: "Tobacco Rage 32",
    brand: "Assaf",
    collection: "Tobacco Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/tobacco-rage-32.jpeg",
  },

  {
    id: 21,
    name: "Wild Colt Tobacco",
    brand: "Assaf",
    collection: "Tobacco Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/Wild_Colt_Tobacco.jpeg",
  },

  {
    id: 22,
    name: "Arrogate Addict",
    brand: "Assaf",
    collection: "Arrogate Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/Arrogate_Addict_Elixir.jpeg",
  },

  {
    id: 23,
    name: "Arrogate Bakhoor",
    brand: "Assaf",
    collection: "Arrogate Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/arrogate-bakhoor.jpeg",
  },

  {
    id: 24,
    name: "Arrogate Blue De",
    brand: "Assaf",
    collection: "Arrogate Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/Arrogate_Blue_De.jpeg",
  },

  {
    id: 25,
    name: "Arrogate Comete",
    brand: "Assaf",
    collection: "Arrogate Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/Arrogate_Comete.jpeg",
  },

  {
    id: 26,
    name: "Arrogate Girl",
    brand: "Assaf",
    collection: "Arrogate Collection",
    gender: "Women",
    price: 1000,
    image: "/products/assaf/arrogate-girl.jpeg",
  },

  {
    id: 27,
    name: "Arrogate Pink",
    brand: "Assaf",
    collection: "Arrogate Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/arrogate-pink.jpeg",
  },

  {
    id: 28,
    name: "Attacks",
    brand: "Assaf",
    collection: "Arrogate Collection",
    gender: "Men",
    price: 1000,
    image: "/products/assaf/attacks.jpeg",
  },

  {
    id: 29,
    name: "Dangerous Arrogate",
    brand: "Assaf",
    collection: "Arrogate Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/Dangerous_Arrogate.jpeg",
  },

  {
    id: 30,
    name: "Glitch",
    brand: "Assaf",
    collection: "Arrogate Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/glitch.jpeg",
  },

  {
    id: 31,
    name: "Miss Arrogate",
    brand: "Assaf",
    collection: "Arrogate Collection",
    gender: "Women",
    price: 1000,
    image: "/products/assaf/Miss_Arrogate.jpeg",
  },

  {
    id: 32,
    name: "Oud Bakhur",
    brand: "Assaf",
    collection: "Bakhoor Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/oud-bakhur.jpeg",
  },

  {
    id: 33,
    name: "Wild Colt Bakhur",
    brand: "Assaf",
    collection: "Bakhoor Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/wild-colt-bakhur.jpeg",
  },

  {
    id: 34,
    name: "Alex",
    brand: "Assaf",
    collection: "Enable Collection",
    gender: "Men",
    price: 1000,
    image: "/products/assaf/alex.jpeg",
  },

  {
    id: 35,
    name: "King",
    brand: "Assaf",
    collection: "Enable Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/king.jpeg",
  },

  {
    id: 36,
    name: "Millionaire",
    brand: "Assaf",
    collection: "Enable Collection",
    gender: "Men",
    price: 1000,
    image: "/products/assaf/millionaire.jpeg",
  },

  {
    id: 37,
    name: "Rebel",
    brand: "Assaf",
    collection: "Enable Collection",
    gender: "Men",
    price: 1000,
    image: "/products/assaf/Rebel_Enable.jpeg",
  },

  {
    id: 38,
    name: "Nomad",
    brand: "Assaf",
    collection: "Enable Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/nomad.jpeg",
  },

  {
    id: 39,
    name: "Pink Queen",
    brand: "Assaf",
    collection: "Enable Collection",
    gender: "Women",
    price: 1000,
    image: "/products/assaf/Pink_Queen.jpeg",
  },

  {
    id: 40,
    name: "Private Purple",
    brand: "Assaf",
    collection: "Enable Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/private-purple.jpeg",
  },

  {
    id: 41,
    name: "Sherlock",
    brand: "Assaf",
    collection: "Enable Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/sherlock.jpeg",
  },

  {
    id: 42,
    name: "Pegasus First Night",
    brand: "Assaf",
    collection: "Pegasus Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/First_Night.jpeg",
  },

  {
    id: 43,
    name: "Pegasus Bakhoor",
    brand: "Assaf",
    collection: "Pegasus Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/pegasus-bakhoor.jpeg",
  },

  {
    id: 44,
    name: "Pegasus Purino",
    brand: "Assaf",
    collection: "Pegasus Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/Pegasus_Proino.jpeg",
  },

  {
    id: 45,
    name: "Pegasus Wild",
    brand: "Assaf",
    collection: "Pegasus Collection",
    gender: "Unisex",
    price: 1000,
    image: "/products/assaf/Wild_Pegasus.jpeg",
  },
];